[project]
name = "engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bentoml>=1.4.24",
    "torch>=2.8.0",
    "transformers>=4.56.2",
]
